#!/usr/bin/env node

import { mkdtemp, readdir, readFile, rename, rm, writeFile } from "node:fs/promises";
import { dirname, isAbsolute, join, relative, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { build } from "esbuild";

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const distDirectory = join(packageRoot, "dist");
const GENERATED_BANNER = [
	"// @generated by scripts/build-runtime.mjs; do not edit.",
	"// @ts-nocheck -- generated JavaScript uses a .ts extension so Pi routes chunks through Jiti.",
].join("\n");

const FORBIDDEN_EAGER_INPUTS = ["src/commands.ts"];
const FORBIDDEN_EAGER_EXTERNALS = new Set(["@narumitw/pi-tui-kit"]);

export async function buildRuntime({ outputDirectory = distDirectory } = {}) {
	const parentDirectory = dirname(outputDirectory);
	const stagingDirectory = await mkdtemp(join(parentDirectory, ".pi-statusline-dist-"));
	try {
		const result = await build({
			absWorkingDir: packageRoot,
			banner: { js: GENERATED_BANNER },
			bundle: true,
			chunkNames: "chunks/[name]-[hash]",
			entryNames: "statusline",
			entryPoints: ["src/statusline.ts"],
			format: "esm",
			legalComments: "none",
			metafile: true,
			outExtension: { ".js": ".ts" },
			outdir: stagingDirectory,
			packages: "external",
			platform: "node",
			splitting: true,
			sourcemap: true,
			target: "es2022",
			write: true,
		});
		validateEagerGraph(result.metafile);
		await rewriteGeneratedSpecifiers(stagingDirectory);
		await validateGeneratedFiles(stagingDirectory);
		await rm(outputDirectory, { force: true, recursive: true });
		await rename(stagingDirectory, outputDirectory);
		return result.metafile;
	} catch (error) {
		await rm(stagingDirectory, { force: true, recursive: true });
		throw error;
	}
}

export function validateEagerGraph(metafile) {
	const outputs = metafile.outputs ?? {};
	const entry = Object.entries(outputs).find(([, output]) =>
		normalizePath(output.entryPoint ?? "").endsWith("/src/statusline.ts"),
	);
	if (!entry) throw new Error("Generated runtime metadata has no pi-statusline entrypoint");

	for (const output of Object.values(outputs)) {
		for (const inputPath of Object.keys(output.inputs ?? {})) {
			const normalized = normalizePath(inputPath);
			if (normalized.includes("/node_modules/")) {
				throw new Error(`Runtime package was bundled: ${normalized}`);
			}
		}
	}

	const eagerOutputs = collectEagerOutputs(outputs, entry[0]);
	const eagerInputs = new Set();
	for (const outputPath of eagerOutputs) {
		const output = outputs[outputPath];
		if (!output) continue;
		for (const inputPath of Object.keys(output.inputs ?? {})) {
			eagerInputs.add(normalizePath(inputPath));
		}
		for (const imported of output.imports ?? []) {
			if (imported.external && FORBIDDEN_EAGER_EXTERNALS.has(imported.path)) {
				throw new Error(`Optional dependency is eager: ${imported.path}`);
			}
		}
	}
	for (const forbidden of FORBIDDEN_EAGER_INPUTS) {
		if ([...eagerInputs].some((input) => input.endsWith(`/${forbidden}`))) {
			throw new Error(`Optional implementation is eager: ${forbidden}`);
		}
	}
	return { eagerInputs, eagerOutputs };
}

function collectEagerOutputs(outputs, entryPath) {
	const eager = new Set();
	const pending = [entryPath];
	while (pending.length > 0) {
		const outputPath = pending.pop();
		if (!outputPath || eager.has(outputPath)) continue;
		eager.add(outputPath);
		for (const imported of outputs[outputPath]?.imports ?? []) {
			if (imported.external || imported.kind === "dynamic-import") continue;
			if (outputs[imported.path]) pending.push(imported.path);
		}
	}
	return eager;
}

async function rewriteGeneratedSpecifiers(outputDirectory) {
	for (const runtimePath of (await listFiles(outputDirectory)).filter((path) =>
		path.endsWith(".ts"),
	)) {
		const path = join(outputDirectory, runtimePath);
		const source = await readFile(path, "utf8");
		const rewritten = source.replace(
			/(["'])(\.\.?\/[^"']+)\.ts\1/gu,
			(_match, quote, specifier) => `${quote}${specifier}.js${quote}`,
		);
		await writeFile(path, rewritten);
	}
}

export async function validateGeneratedFiles(outputDirectory) {
	const files = await listFiles(outputDirectory);
	const runtimeFiles = files.filter((path) => path.endsWith(".ts"));
	if (!runtimeFiles.some((path) => path === "statusline.ts")) {
		throw new Error("Generated runtime is missing statusline.ts");
	}
	for (const runtimePath of runtimeFiles) {
		const source = await readFile(join(outputDirectory, runtimePath), "utf8");
		if (!source.startsWith(GENERATED_BANNER)) {
			throw new Error(`Generated marker is missing from ${runtimePath}`);
		}
		if (/(["'])\.\.?\/[^"']+\.ts\1/u.test(source)) {
			throw new Error(`Generated runtime retains a .ts import specifier in ${runtimePath}`);
		}
		if (!files.includes(`${runtimePath}.map`)) {
			throw new Error(`Source map is missing for ${runtimePath}`);
		}
	}
}

async function listFiles(directory, prefix = "") {
	const files = [];
	for (const entry of await readdir(join(directory, prefix), { withFileTypes: true })) {
		const relativePath = join(prefix, entry.name);
		if (entry.isDirectory()) files.push(...(await listFiles(directory, relativePath)));
		else if (entry.isFile()) files.push(relativePath.replaceAll("\\", "/"));
	}
	return files.sort();
}

function normalizePath(path) {
	const normalized = path.replaceAll("\\", "/");
	if (!isAbsolute(path)) return `/${normalized.replace(/^\.\//u, "")}`;
	return `/${relative(packageRoot, path).replaceAll("\\", "/")}`;
}

const invokedPath = process.argv[1] ? pathToFileURL(resolve(process.argv[1])).href : undefined;
if (invokedPath === import.meta.url) {
	await buildRuntime();
}
